class AppConfig {
  static const String appName = 'DiviSync';
  static const String appVersion = '1.0.0';
  static const String appDescription = 'Professional Currency Conversion App';
  
  // API Configuration
  static const String fixerApiUrl = 'https://data.fixer.io/api';
  static const String exchangeHostApiUrl = 'https://api.exchangerate.host';
  static const String fixerApiKey = 'YOUR_FIXER_API_KEY_HERE';
  
  // Cache Configuration
  static const Duration cacheTtl = Duration(hours: 1);
  static const Duration updateInterval = Duration(hours: 1);
  
  // App Configuration
  static const int maxHistoryItems = 100;
  static const int maxFavorites = 20;
  static const double defaultSpread = 0.0;
  
  // Supported Currencies (ISO 4217)
  static const List<String> supportedCurrencies = [
    'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'SEK', 'NZD',
    'MXN', 'SGD', 'HKD', 'NOK', 'TRY', 'RUB', 'INR', 'BRL', 'ZAR', 'KRW',
    'DKK', 'PLN', 'TWD', 'THB', 'MYR', 'PHP', 'IDR', 'HUF', 'CZK', 'ILS',
    'CLP', 'PKR', 'BGN', 'RON', 'ISK', 'HRK', 'UAH', 'LTL', 'LVL', 'EEK',
    'COP', 'ARS', 'PEN', 'UYU', 'BOB', 'VEF', 'PYG', 'GTQ', 'HNL', 'NIO',
    'CRC', 'PAB', 'DOP', 'JMD', 'TTD', 'BBD', 'XCD', 'AWG', 'KYD', 'BZD',
    'BMD', 'BAM', 'MKD', 'RSD', 'MNT', 'AMD', 'GEL', 'AZN', 'KZT', 'UZS',
    'KGS', 'TJS', 'TMT', 'AFN', 'PKR', 'LKR', 'BDT', 'NPR', 'BTN', 'MVR',
    'SCR', 'MUR', 'KMF', 'DJF', 'ETB', 'SOS', 'TZS', 'UGX', 'RWF', 'BIF',
    'CDF', 'AOA', 'ZMW', 'BWP', 'SZL', 'LSL', 'NAD', 'MAD', 'TND', 'DZD',
    'LYD', 'SDG', 'SSP', 'EGP', 'ETB', 'ERI', 'DJI', 'SOM', 'YER', 'OMR',
    'QAR', 'BHD', 'KWD', 'AED', 'SAR', 'JOD', 'LBP', 'SYP', 'IQD', 'IRR',
    'AFN', 'PKR', 'INR', 'BDT', 'LKR', 'NPR', 'BTN', 'MVR', 'SCR', 'MUR',
  ];
  
  // Currency Display Names
  static const Map<String, String> currencyNames = {
    'USD': 'US Dollar',
    'EUR': 'Euro',
    'GBP': 'British Pound',
    'JPY': 'Japanese Yen',
    'AUD': 'Australian Dollar',
    'CAD': 'Canadian Dollar',
    'CHF': 'Swiss Franc',
    'CNY': 'Chinese Yuan',
    'SEK': 'Swedish Krona',
    'NZD': 'New Zealand Dollar',
    'MXN': 'Mexican Peso',
    'SGD': 'Singapore Dollar',
    'HKD': 'Hong Kong Dollar',
    'NOK': 'Norwegian Krone',
    'TRY': 'Turkish Lira',
    'RUB': 'Russian Ruble',
    'INR': 'Indian Rupee',
    'BRL': 'Brazilian Real',
    'ZAR': 'South African Rand',
    'KRW': 'South Korean Won',
    'DKK': 'Danish Krone',
    'PLN': 'Polish Zloty',
    'TWD': 'Taiwan Dollar',
    'THB': 'Thai Baht',
    'MYR': 'Malaysian Ringgit',
    'PHP': 'Philippine Peso',
    'IDR': 'Indonesian Rupiah',
    'HUF': 'Hungarian Forint',
    'CZK': 'Czech Koruna',
    'ILS': 'Israeli Shekel',
    'CLP': 'Chilean Peso',
    'PKR': 'Pakistani Rupee',
    'BGN': 'Bulgarian Lev',
    'RON': 'Romanian Leu',
    'ISK': 'Icelandic Krona',
    'HRK': 'Croatian Kuna',
    'UAH': 'Ukrainian Hryvnia',
    'COP': 'Colombian Peso',
    'ARS': 'Argentine Peso',
    'PEN': 'Peruvian Sol',
    'UYU': 'Uruguayan Peso',
    'BOB': 'Bolivian Boliviano',
    'VEF': 'Venezuelan Bolivar',
    'PYG': 'Paraguayan Guarani',
    'GTQ': 'Guatemalan Quetzal',
    'HNL': 'Honduran Lempira',
    'NIO': 'Nicaraguan Cordoba',
    'CRC': 'Costa Rican Colon',
    'PAB': 'Panamanian Balboa',
    'DOP': 'Dominican Peso',
    'JMD': 'Jamaican Dollar',
    'TTD': 'Trinidad and Tobago Dollar',
    'BBD': 'Barbadian Dollar',
    'XCD': 'East Caribbean Dollar',
    'AWG': 'Aruban Florin',
    'KYD': 'Cayman Islands Dollar',
    'BZD': 'Belize Dollar',
    'BMD': 'Bermudian Dollar',
    'BAM': 'Bosnia and Herzegovina Convertible Mark',
    'MKD': 'Macedonian Denar',
    'RSD': 'Serbian Dinar',
    'MNT': 'Mongolian Tugrik',
    'AMD': 'Armenian Dram',
    'GEL': 'Georgian Lari',
    'AZN': 'Azerbaijani Manat',
    'KZT': 'Kazakhstani Tenge',
    'UZS': 'Uzbekistani Som',
    'KGS': 'Kyrgyzstani Som',
    'TJS': 'Tajikistani Somoni',
    'TMT': 'Turkmenistani Manat',
    'AFN': 'Afghan Afghani',
    'LKR': 'Sri Lankan Rupee',
    'BDT': 'Bangladeshi Taka',
    'NPR': 'Nepalese Rupee',
    'BTN': 'Bhutanese Ngultrum',
    'MVR': 'Maldivian Rufiyaa',
    'SCR': 'Seychellois Rupee',
    'MUR': 'Mauritian Rupee',
    'KMF': 'Comorian Franc',
    'DJF': 'Djiboutian Franc',
    'ETB': 'Ethiopian Birr',
    'SOS': 'Somali Shilling',
    'TZS': 'Tanzanian Shilling',
    'UGX': 'Ugandan Shilling',
    'RWF': 'Rwandan Franc',
    'BIF': 'Burundian Franc',
    'CDF': 'Congolese Franc',
    'AOA': 'Angolan Kwanza',
    'ZMW': 'Zambian Kwacha',
    'BWP': 'Botswana Pula',
    'SZL': 'Swazi Lilangeni',
    'LSL': 'Lesotho Loti',
    'NAD': 'Namibian Dollar',
    'MAD': 'Moroccan Dirham',
    'TND': 'Tunisian Dinar',
    'DZD': 'Algerian Dinar',
    'LYD': 'Libyan Dinar',
    'SDG': 'Sudanese Pound',
    'SSP': 'South Sudanese Pound',
    'EGP': 'Egyptian Pound',
    'ERI': 'Eritrean Nakfa',
    'DJI': 'Djiboutian Franc',
    'SOM': 'Somali Shilling',
    'YER': 'Yemeni Rial',
    'OMR': 'Omani Rial',
    'QAR': 'Qatari Riyal',
    'BHD': 'Bahraini Dinar',
    'KWD': 'Kuwaiti Dinar',
    'AED': 'UAE Dirham',
    'SAR': 'Saudi Riyal',
    'JOD': 'Jordanian Dinar',
    'LBP': 'Lebanese Pound',
    'SYP': 'Syrian Pound',
    'IQD': 'Iraqi Dinar',
    'IRR': 'Iranian Rial',
  };
  
  // Currency Symbols
  static const Map<String, String> currencySymbols = {
    'USD': '\$',
    'EUR': '€',
    'GBP': '£',
    'JPY': '¥',
    'AUD': 'A\$',
    'CAD': 'C\$',
    'CHF': 'CHF',
    'CNY': '¥',
    'SEK': 'kr',
    'NZD': 'NZ\$',
    'MXN': '\$',
    'SGD': 'S\$',
    'HKD': 'HK\$',
    'NOK': 'kr',
    'TRY': '₺',
    'RUB': '₽',
    'INR': '₹',
    'BRL': 'R\$',
    'ZAR': 'R',
    'KRW': '₩',
    'DKK': 'kr',
    'PLN': 'zł',
    'TWD': 'NT\$',
    'THB': '฿',
    'MYR': 'RM',
    'PHP': '₱',
    'IDR': 'Rp',
    'HUF': 'Ft',
    'CZK': 'Kč',
    'ILS': '₪',
    'CLP': '\$',
    'PKR': '₨',
    'BGN': 'лв',
    'RON': 'lei',
    'ISK': 'kr',
    'HRK': 'kn',
    'UAH': '₴',
    'COP': '\$',
    'ARS': '\$',
    'PEN': 'S/',
    'UYU': '\$U',
    'BOB': 'Bs',
    'VEF': 'Bs.S',
    'PYG': '₲',
    'GTQ': 'Q',
    'HNL': 'L',
    'NIO': 'C\$',
    'CRC': '₡',
    'PAB': 'B/.',
    'DOP': 'RD\$',
    'JMD': 'J\$',
    'TTD': 'TT\$',
    'BBD': 'Bds\$',
    'XCD': 'EC\$',
    'AWG': 'ƒ',
    'KYD': 'CI\$',
    'BZD': 'BZ\$',
    'BMD': 'BD\$',
    'BAM': 'КМ',
    'MKD': 'ден',
    'RSD': 'дин',
    'MNT': '₮',
    'AMD': '֏',
    'GEL': '₾',
    'AZN': '₼',
    'KZT': '₸',
    'UZS': 'сўм',
    'KGS': 'сом',
    'TJS': 'SM',
    'TMT': 'T',
    'AFN': '؋',
    'LKR': '₨',
    'BDT': '৳',
    'NPR': '₨',
    'BTN': 'Nu.',
    'MVR': 'ރ',
    'SCR': '₨',
    'MUR': '₨',
    'KMF': 'CF',
    'DJF': 'Fdj',
    'ETB': 'Br',
    'SOS': 'S',
    'TZS': 'TSh',
    'UGX': 'USh',
    'RWF': 'RF',
    'BIF': 'FBu',
    'CDF': 'FC',
    'AOA': 'Kz',
    'ZMW': 'ZK',
    'BWP': 'P',
    'SZL': 'E',
    'LSL': 'L',
    'NAD': 'N\$',
    'MAD': 'د.م.',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'LYD': 'ل.د',
    'SDG': 'ج.س.',
    'SSP': '£',
    'EGP': '£',
    'ERI': 'Nfk',
    'DJI': 'Fdj',
    'SOM': 'S',
    'YER': '﷼',
    'OMR': 'ر.ع.',
    'QAR': 'ر.ق',
    'BHD': 'د.ب',
    'KWD': 'د.ك',
    'AED': 'د.إ',
    'SAR': 'ر.س',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'SYP': 'ل.س',
    'IQD': 'د.ع',
    'IRR': '﷼',
  };
  
  // Currency Decimal Places
  static const Map<String, int> currencyDecimals = {
    'USD': 2,
    'EUR': 2,
    'GBP': 2,
    'JPY': 0,
    'AUD': 2,
    'CAD': 2,
    'CHF': 2,
    'CNY': 2,
    'SEK': 2,
    'NZD': 2,
    'MXN': 2,
    'SGD': 2,
    'HKD': 2,
    'NOK': 2,
    'TRY': 2,
    'RUB': 2,
    'INR': 2,
    'BRL': 2,
    'ZAR': 2,
    'KRW': 0,
    'DKK': 2,
    'PLN': 2,
    'TWD': 2,
    'THB': 2,
    'MYR': 2,
    'PHP': 2,
    'IDR': 0,
    'HUF': 2,
    'CZK': 2,
    'ILS': 2,
    'CLP': 0,
    'PKR': 2,
    'BGN': 2,
    'RON': 2,
    'ISK': 0,
    'HRK': 2,
    'UAH': 2,
    'COP': 0,
    'ARS': 2,
    'PEN': 2,
    'UYU': 2,
    'BOB': 2,
    'VEF': 2,
    'PYG': 0,
    'GTQ': 2,
    'HNL': 2,
    'NIO': 2,
    'CRC': 2,
    'PAB': 2,
    'DOP': 2,
    'JMD': 2,
    'TTD': 2,
    'BBD': 2,
    'XCD': 2,
    'AWG': 2,
    'KYD': 2,
    'BZD': 2,
    'BMD': 2,
    'BAM': 2,
    'MKD': 2,
    'RSD': 2,
    'MNT': 2,
    'AMD': 2,
    'GEL': 2,
    'AZN': 2,
    'KZT': 2,
    'UZS': 2,
    'KGS': 2,
    'TJS': 2,
    'TMT': 2,
    'AFN': 2,
    'LKR': 2,
    'BDT': 2,
    'NPR': 2,
    'BTN': 2,
    'MVR': 2,
    'SCR': 2,
    'MUR': 2,
    'KMF': 0,
    'DJF': 0,
    'ETB': 2,
    'SOS': 2,
    'TZS': 2,
    'UGX': 0,
    'RWF': 0,
    'BIF': 0,
    'CDF': 2,
    'AOA': 2,
    'ZMW': 2,
    'BWP': 2,
    'SZL': 2,
    'LSL': 2,
    'NAD': 2,
    'MAD': 2,
    'TND': 3,
    'DZD': 2,
    'LYD': 3,
    'SDG': 2,
    'SSP': 2,
    'EGP': 2,
    'ERI': 2,
    'DJI': 0,
    'SOM': 2,
    'YER': 2,
    'OMR': 3,
    'QAR': 2,
    'BHD': 3,
    'KWD': 3,
    'AED': 2,
    'SAR': 2,
    'JOD': 3,
    'LBP': 2,
    'SYP': 2,
    'IQD': 3,
    'IRR': 2,
  };
}
